kind: Service
apiVersion: v1
metadata:
  name: nginx-k8s
  labels:
    app: nginx-k8s
spec:
  type: NodePort
  selector:
    app: nginx-k8s
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
